name: sparkrdd
services:
  spark-master:
    image: bitnamilegacy/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    user: root
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - .:/opt/bitnami/spark/app
      - outputs:/opt/bitnami/spark/output
      - ./conf:/opt/bitnami/spark/conf
  spark-worker-1:
    image: bitnamilegacy/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    user: root
    ports:
      - "9091:8081"
    depends_on:
      - spark-master
    volumes:
      - .:/opt/bitnami/spark/app
      - outputs:/opt/bitnami/spark/output
      - ./conf:/opt/bitnami/spark/conf
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-worker-2:
    image: bitnamilegacy/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    user: root
    ports:
      - "9092:8081"
    depends_on:
      - spark-master
    volumes:
      - .:/opt/bitnami/spark/app
      - outputs:/opt/bitnami/spark/output
      - ./conf:/opt/bitnami/spark/conf
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-history:
    image: bitnamilegacy/spark:latest
    command: bin/spark-class org.apache.spark.deploy.history.HistoryServer
    user: root
    ports:
      - "18080:18080"
    volumes:
      - outputs:/opt/bitnami/spark/output
      - ./conf:/opt/bitnami/spark/conf
    depends_on:
      - spark-master
volumes:
  outputs: 